Qhull 2012.1  2012/02/18 6.3.1.1490
Code changes
 - Require option 'Qz' for Delaunay triangulation/Voronoi diagram
   of cocircular/cospherical points [D. Sheehy]
 - qh_errexit: Do not call qh_printsummary or qh_printstats on qh_ERRinput
 - Change error QH6227 (all degenerate) from qh_ERRinput to qh_ERRprec
 - Change error QH6159 (ID overflow) from qh_ERRinput to qh_ERRqhull
 - eg/q_eg, q_egtest, q_test: Run if qconvex is in $PATH [M. Atzeri]

Build changes [M. Atzeri]
 - Install to share/doc/qhull instead of share/doc/packages/qhull
 - On Unix systems, install to share/man/man1 instead of man/man1
 - CMakeLists: Remove the installation of user_eg* and testqset
 - CMakeLists: Remove VERSION from qhull executables and libraries
 - CMakeLists: Define qhull_SOVERSION instead of qhull_MAJOR
 - CMakeLists: Set SOVERSION for shared libraries
 - Rename libraries to qhull, qhull_d, qhull_p, and qhull_pd
   libqhull6_p.vcproj is now libqhull_p.vcproj
   mingw builds as libqhull.dll
   cygwin builds as cygqhull-6.dll
   linux builds as libqhull.so.6.3.1 with symbolic link as libqhull.so
 - Developers using qhull 2011:
   libqhull6.so is now libqhull_p.so.  Do not use libqhull.so.
   qhull6.dll is now qhull_p.dll.  Do not use qhull.dll.
 - Merged road/ into libqhullcpp/ and qhulltest/
   Moved RoadLogEvent.* and RoadError.* to libqhullcpp
   Moved RoadTest.* to qhulltest (requires Qt)
   Installed RoadTest.h in libqhullcpp

Doc changes
 - index.htm: Mathworks uses qhull for n-d
 - qhull.htm: Fix qhull for qconvex
 - qdelaun.htm/qvoronoi.htm: Use option 'Qz' for circular/cospherical inputs
 - make help: Display targets
 - Makefile: Better messaging

diff --git a/eg/q_eg b/eg/q_eg
--- a/eg/q_eg
+++ b/eg/q_eg
@@ -1,17 +1,20 @@
 #!/bin/sh
 #   writes examples to eg/
 #   see html/qh_eg.htm
-if [ ! -d bin ]; then
-    echo Run eg/q_eg from the Qhull directory
-    exit
-fi
-if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
-    echo Build qhull first.  Executables are missing from bin directory
-    exit
-fi
 if ! qconvex >/dev/null 2>&1; then
-    PATH=$PWD/bin:$PATH
+    if [ ! -d bin ]; then
+	echo Run eg/q_eg from the Qhull directory
+	exit
+    fi
+    if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
+	echo 'Build qhull first.  qconvex is missing from bin/ directory and $PATH'
+	exit
+    fi
+    if ! qconvex >/dev/null 2>&1; then
+	PATH=$PWD/bin:$PATH
+    fi
 fi
+mkdir -p eg
 set -v
 rbox c D3 | qconvex s G >eg/eg.01.cube
 rbox c d G2.0 | qconvex s G >eg/eg.02.diamond.cube
diff --git a/eg/q_egtest b/eg/q_egtest
--- a/eg/q_egtest
+++ b/eg/q_egtest
@@ -1,16 +1,19 @@
 #!/bin/sh
 #   writes examples to eg/
-if [ ! -d bin ]; then
-    echo Run eg/q_eg from the Qhull directory
-    exit
-fi
-if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
-    echo Build qhull first.  Executables are missing from bin directory
-    exit
-fi
 if ! qconvex >/dev/null 2>&1; then
-    PATH=$PWD/bin:$PATH
+    if [ ! -d bin ]; then
+	echo Run eg/q_eg from the Qhull directory
+	exit
+    fi
+    if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
+	echo 'Build qhull first.  qconvex is missing from bin/ directory and $PATH'
+	exit
+    fi
+    if ! qconvex >/dev/null 2>&1; then
+	PATH=$PWD/bin:$PATH
+    fi
 fi
+mkdir -p
 set -v
 rbox d D3 | qconvex s Gnrv Tc Tv >eg/eg.t01.spheres.3
 rbox d D2 | qconvex s Gnv  Tc Tv >eg/eg.t02.spheres.2
diff --git a/eg/q_test b/eg/q_test
--- a/eg/q_test
+++ b/eg/q_test
@@ -1,21 +1,22 @@
 #!/bin/sh
 #
 #  NOTE:  all tests duplicated in q_test.bat
-if [ ! -d bin ]; then
-    echo Run eg/q_test from the Qhull directory
-    exit
-fi
-if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
-    echo Build qhull first.  Executables are missing from bin directory
-    exit
-fi
 if ! qconvex >/dev/null 2>&1; then
-    PATH=$PWD/bin:$PATH
+    if [ ! -d bin ]; then
+	echo Run eg/q_test from the Qhull directory
+	exit
+    fi
+    if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
+	echo 'Build qhull first.  qconvex is missing from bin/ directory and $PATH'
+	exit
+    fi
+    if ! qconvex >/dev/null 2>&1; then
+	PATH=$PWD/bin:$PATH
+    fi
 fi
 if ! user_eg >/dev/null; then
     echo user_eg failed to run.  It uses the shared qhull library 
     echo 'On Linux, export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH'
-    exit
 fi
 set -v
 echo === errors if 'user_eg' and 'user_eg2' not found ===
